format_version: 10
pipelines:
  expense-create:
    group: Terraform
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-68ec9f0:
        git: https://github.com/devopsinnovation/expense-terraform
        shallow_clone: true
        auto_update: true
        branch: main
    stages:
      - DEV:
          fetch_materials: true
          environment_variables:
            env: dev
            component: backend
            pipeline: true
          clean_workspace: false
          jobs:
            ansible:
              timeout: 0
              tasks:
                - exec: { command: terraform, arguments: [ "init", "-backend-config", "env-dev/state.tfvars" ]  }
                - exec: { command: terraform, arguments: [ "apply", "-var-file", "env-dev/state.tfvars", "-auto-approve" ]  }

      - PROD:
          fetch_materials: true
          environment_variables:
            env: dev
            component: backend
            pipeline: true
          clean_workspace: false
          jobs:
            ansible:
              timeout: 0
              tasks:
                - exec: { command: terraform, arguments: [ "init", "-backend-config", "env-dev/state.tfvars" ]  }
                - exec: { command: terraform, arguments: [ "apply", "-var-file", "env-dev/state.tfvars", "-auto-approve" ]  }