format_version: 10
pipelines:
  backend:
    group: APP-Deployments
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-68ec9f0:
        git: https://github.com/devopsinnovation/ansible-expense-dry-code
        shallow_clone: true
        auto_update: true
        branch: main
    stages:
      - DEV:
          fetch_materials: true
          clean_workspace: false
          jobs:
            ansible:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                    - -i
                    - backend-dev.devopsinnovation.online,
                    - -e
                    - ansible_user=ec2-user
                    - -e
                    - ansible_password=DevOps321
                    - -e
                    - env=dev
                    - -e
                    - role_name=backend
                    - expense.yml
                    command: ansible-playbook

      - QA:
          fetch_materials: true
          clean_workspace: false
          approval:
            type: manual
          jobs:
            ansible:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - -l
                    command: ls
                    run_if: passed

      - STAGE:
          fetch_materials: true
          clean_workspace: false
          jobs:
            ansible:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - -l
                    command: ls
                    run_if: passed
      - PROD:
          fetch_materials: true
          clean_workspace: false
          jobs:
            ansible:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - -l
                    command: ls
                    run_if: passed