format_version: 10
pipelines:
  MYSQL:
    group: APP-Deployments
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-68ec9f0:
        git: https://github.com/devopsinnovation/ansible-expense-dry-code
        shallow_clone: true
        auto_update: true
        branch: main
    secure_variables:
      SSH_PASSWORD: "AES:KaiVssqD/akeUFTZ51l2lw==:tRG3Xs0o7Pp0nKbBX1supQ=="
    stages:
      - DEV:
          fetch_materials: true
          clean_workspace: false
          jobs:
            ansible:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - -i
                      - mysql-dev.devopsinnovation.online,
                      - -e
                      - ansible_user=ec2-user
                      - -e
                        - ansible_password=${SSH_PASSWORD}
                      - -e
                      - env=dev
                      - -e
                      - role_name=mysql
                      - expense.yml
                    command: ansible-playbook

      - QA:
          fetch_materials: true
          clean_workspace: false
          approval:
            type: manual
          jobs:
            ansible:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - -l
                    command: ls
                    run_if: passed

      - STAGE:
          fetch_materials: true
          clean_workspace: false
          jobs:
            ansible:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - -l
                    command: ls
                    run_if: passed
      - PROD:
          fetch_materials: true
          clean_workspace: false
          jobs:
            ansible:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - -l
                    command: ls
                    run_if: passed